# Generated by Django 4.2.4 on 2023-08-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityprice',
            name='earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
