# Generated by Django 4.2.4 on 2023-08-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_sharing', '0002_electricityprice_earnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricityprice',
            old_name='earnings',
            new_name='earnings_per_our',
        ),
    ]
