# Generated by Django 4.2.4 on 2023-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_sharing', '0003_rename_earnings_electricityprice_earnings_per_our'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricityprice',
            old_name='earnings_per_our',
            new_name='daily_average_price',
        ),
        migrations.AddField(
            model_name='electricityprice',
            name='earnings_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
